### ISSUE TITLE
Create a new service for generating incremental form IDs

### ISSUE THREAD

**Issue by hasanhaja** [hasancruk/form-builder#9]
# Todo

- [x] Create corresponding stack and endpoint 
- [x] Implement trpc boilerplate 
- [x] Implement database with the following columns: formId, url/name archived/active
- [ ] Implement the following functionality 
  - [ ] a procedure to create a new form that accepts a schema (without formid) and returns an object that is the schema plus formid. This should also add to a database the formid and the form name, so that neither the id nor the form name can be duplicated. 
  - [ ] a mutation to archive and I archive forms (this means that archived forms shouldn't be fetchable; should this be a separate service?)
  - [ ] a mutation to update form name (url) (so when the request comes in, it should be the entire form object so it can be returned back to be updated in s3)
- [ ] Evaluate the responsibility of this service and the other services and combine if and where appropriate
